
local Constants = {
	
	-- SQUAD
	SQUAD_TIME_TO_DOWN 		= 15,
	SQUAD_DOWN_DISTANCE 	= 10,
	SQUAD_MIN_X 			= 8,
	SQUAD_MAX_X 			= 192,
	SQUAD_SPEED 			= 16,

	-- INVADER
	INVADER_COOLDOWN 		= 3,
	INVADER_SHOOT_SPEED 	= 96,

	-- HUMAN
	HUMAN_COOLDOWN 			= 0.5,
	HUMAN_SPEED 			= 32,
	HUMAN_HEALTH 			= 1,
	HUMAN_START_X 			= 100,
	HUMAN_START_Y 			= 8,
	HUMAN_SHOOT_SPEED 		= 128,

	-- SHIELD
	SHIELD_HEALTH 			= 64,

	-- BULLETS
	BULLET_HUMAN 			= 0xDEADBEEF,
	BULLET_INVADER 			= 0xFACEFEED,

	-- COSTS
	SCORE_HIT_SHIELD 		= 10,
	SCORE_BREAK_SHIELD 		= 100,
	SCORE_HIT_HUMAN 		= 100,
	SCORE_KILL_HUMAN 		= 100000,
	COST_CREATE_INVADER 	= 50000,
	COST_UPGRADE_INVADER1 	= 1000,
	COST_UPGRADE_INVADER2 	= 2000,

	-- PROGRESSION
	LEVEL1_NUM_HUMANS 		= 1,
	LEVEL2_NUM_HUMANS 		= 1,
	LEVEL3_NUM_HUMANS 		= 2,

	LEVEL1_HUMAN_HEALTH 	= 30,
	LEVEL2_HUMAN_HEALTH 	= 40,
	LEVEL3_HUMAN_HEALTH 	= 50,

	LEVEL1_HUMAN_SHOOTS 	= 2,
	LEVEL2_HUMAN_SHOOTS 	= 3,
	LEVEL3_HUMAN_SHOOTS 	= 3,

	LEVEL1_HUMAN_SPEED 		= 32,
	LEVEL2_HUMAN_SPEED 		= 64,
	LEVEL3_HUMAN_SPEED 		= 48,

}

return Constants
