
local Constants = {
	
	-- SQUAD
	SQUAD_TIME_TO_DOWN 		= 5,
	SQUAD_DOWN_DISTANCE 	= 10,
	SQUAD_MIN_X 			= 8,
	SQUAD_MAX_X 			= 192,

	-- INVADER
	INVADER_COOLDOWN 		= 3,

	-- HUMAN
	HUMAN_COOLDOWN 			= 0.5,
	HUMAN_SPEED 			= 1,
	HUMAN_HEALTH 			= 10,
	HUMAN_START_X 			= 100,
	HUMAN_START_Y 			= 132,

	-- SHIELD
	SHIELD_HEALTH 			= 5,

	-- BULLETS
	BULLET_HUMAN 			= 0xDEADBEEF,
	BULLET_INVADER 			= 0xFACEFEED,

}

return Constants
